### PR TITLE
Updated code so that is catch up new version of pep8.

### PR DESCRIPTION
**Pull request by xliiv**
Before, there were a few lambda assignments.
Now, they are changed with regular functions.
Fix made for pep8 compatibility.

### CODE REVIEW

**Comment by mkurek** [comment]
if there is nothing dynamic in this functions (they are just returning static content) why they are functions, not variables?

**Comment by xliiv** [comment]
To ensure their values are always like in the function.
Perhaps it could be achieved by simple coping. However i can't see other reason then purity for changing it.

**Comment by ar4s** [comment]
:OK:

**Comment by mkurek** [comment]
:ok:

**Pull request merged**
